name: screenshot_detect
description: An iOS package for detecting when a user takes a screenshot and adding listeners to that action.
version: 1.0.4
homepage: https://github.com/glebosotov/flutter-screenshot-callback

environment:
    sdk: ^3.8.1
    flutter: ">=3.0.0"

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0
    pigeon: ^25.3.2

flutter:
    plugin:
        platforms:
            ios:
                pluginClass: ScreenshotDetectPlugin
